=== AkashPawar-A/restassured-api-automationframework/RestAssuredApiTesting.BDD/src/test/resources/requestSchemas_files/MaterialPurchase.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title" : "Material Purchase",
  "type": "object",
  "additionalProperties": false,

  "required": [
    "remark",
    "purchase_date",
    "vendor_reference_number",
    "party_company_user_id",
    "project_id",
    "material_amount",
    "gst_amount",
    "other_amount",
    "discount",
    "total_payable",
    "net_amount",
    "materials"
  ],

  "properties": {
    "remark": { "type": "string" },
    "purchase_date": { "type": "string", "format": "date-time" },
    "vendor_reference_number": { "type": "string" },
    "party_company_user_id": { "type": "string", "format": "uuid" },
    "project_id": { "type": "string", "format": "uuid" },
    "sub_category_id": { "type": ["string", "null"], "format": "uuid" },
    "due_days": { "type": ["integer", "null"] },
    "ship_to_address_id": { "type": ["string", "null"], "format": "uuid" },
    "bill_to_address_id": { "type": ["string", "null"], "format": "uuid" },
    "ship_from_address_id": { "type": ["string", "null"], "format": "uuid" },
    "bill_from_address_id": { "type": ["string", "null"], "format": "uuid" },
    "material_amount": { "type": "number" },
    "gst_amount": { "type": "number" },
    "other_amount": { "type": "number" },
    "discount": { "type": "number" },
    "total_payable": { "type": "number" },
    "net_amount": { "type": "number" },
    "is_roundoff": { "type": ["integer", "null"] },
    "other_amount_gst_percentage": { "type": ["number", "null"] },
    "other_amount_gst_amount": { "type": ["number", "null"] },
    "other_amount_text": { "type": ["string", "null"] },
    "photos": { "type": "array", "items": { "type": "string" } },
    
    "materials": { "type": "array", "minItems": 1,
      "items": { "type": "object", "additionalProperties": false,
        "required": [
          "material_item_id",
          "materialstock_id",
          "type",
          "name",
          "quantity",
          "unit",
          "unit_price",
          "gst_percent",
          "gst_amount",
          "discount_amount",
          "total_payable",
          "receiving_date",
          "is_purchase",
          "photos"
        ],

        "properties": {
          "material_item_id": { "type": "string", "format": "uuid" },
          "materialstock_id": { "type": "string", "format": "uuid" },
          "type": { "type": "string" },
          "name": { "type": "string" },
          "quantity": { "type": "number" },
          "unit": { "type": "string" },
          "unit_price": { "type": "number" },
          "gst_percent": { "type": "number" },
          "gst_amount": { "type": "number" },
          "discount_amount": { "type": "number" },
          "total_payable": { "type": "number" },
          "receiving_date": { "type": "string", "format": "date-time" },
          "is_purchase": { "type": "integer" },
          "is_material_returned": { "type": ["integer", "null"] },
          "is_material_sold": { "type": ["integer", "null"] },
          "notes": { "type": ["string", "null"] },
          "hsn_code": { "type": ["string", "null"] },
          "item_code": { "type": ["string", "null"] },
          "photos": { "type": "array", "items": { "type": "string" }
          }
        }
      }
    }
  }
}

=== AkashPawar-A/restassured-api-automationframework/RestAssuredApiTesting.BDD/src/test/resources/testdata_materialpurchase/add_materialpurchase.json
{
  "remark": "test - 2",
  "purchase_date": "2026-05-04T11:11:45.175Z",
  "vendor_reference_number": "A-01",
  "party_company_user_id": "ad68f28f-e84c-4ceb-9991-1dffd745f3c1",
  "project_id": "a43a10ac-fa91-4ec3-ba8f-ac1dc944c4c9",
  "sub_category_id": null,
  "due_days": null,
  "ship_to_address_id": null,
  "bill_to_address_id": null,
  "ship_from_address_id": null,
  "bill_from_address_id": null,
  "material_amount": 970,
  "gst_amount": 174.6,
  "other_amount": 10,
  "discount": 20,
  "total_payable": 1134.6,
  "net_amount": 1134.6,
  "is_roundoff": 0,
  "other_amount_gst_percentage": 0,
  "other_amount_gst_amount": 0,
  "other_amount_text": "Additional Charges - test 1",
  "photos": [],
  "materials": []
}
